export const UPDATE_USER = 'UPDATE_USER';
export const ADD_NEW_NOTE = 'ADD_NEW_NOTE';
export const SET_NOTE_ACTIVE = 'SET_NOTE_ACTIVE';
export const SET_ACTIVE_NOTE_VALUE = 'SET_ACTIVE_NOTE_VALUE';
export const SET_NOTE_TITLE = 'SET_NOTE_TITLE';
export const STORE_NOTES_LIST = 'STORE_NOTES_LIST';
